// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { Piece } from "./Piece";
import type { PieceColor } from "./PieceColor";
import type { Position } from "./Position";

export interface Board { pieces: Array<Piece>, turn: PieceColor, selected_piece: Position | null, game_state: GameState, white_castle_kingside: boolean, white_castle_queenside: boolean, black_castle_kingside: boolean, black_castle_queenside: boolean, en_passant: Position | null, bot: PieceColor, }