// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineAlpha } from "./Alpha";
import type { Minimax } from "./Minimax";
import type { Piece } from "../../src/bindings/Piece";
import type { PieceColor } from "../../src/bindings/PieceColor";
import type { Position } from "../../src/bindings/Position";

export interface Board { pieces: Array<Piece>, selected: Position | null, en_passant: Position | null, castles: [boolean, boolean, boolean, boolean], turn: PieceColor, engine: EngineAlpha, bot_color: PieceColor, bot: Minimax, }