// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveKind = "Move" | "Capture" | "EnPassant" | "Dash" | "Castle" | "Promotion"; "BlackInCheckmate" | "Stalemate" | "Other";