// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameState = "Playing" | "WhiteCheck" | "BlackCheck" | "WhiteCheckmate" | "BlackCheckmate" | "Stalemate" | "Error";