// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsFunction = "None" | "CreatePiece" | "MovePiece" | "DeletePiece" | "PromotePiece" | "DeleteBoard" | "CreateHighlight" | "DeleteHighlights" | "CallChessBot" | "GameOver";