// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { PieceKind } from "./PieceKind";
import type { Position } from "./Position";

export interface Piece { position: Position, color: PieceColor, kind: PieceKind, pid: number, }