// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { PieceKind } from "./PieceKind";

export interface Piece { kind: PieceKind, color: PieceColor, }